name: Main workflow
on: push   #Event 

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the node js project
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 16
          fetch-depth: 0
      - run: npm install
      - run: npm run build --if-present
  sonarcloud:
    runs-on: ubuntu-latest
    name: SAST scan (SonarCloud)
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}